version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: lab_mongo
    ports:
      - '27017:27017'
    volumes:
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/init.js:ro

  mongo-express:
    image: mongo-express
    container_name: lab_mongo_express
    depends_on:
      - mongo
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab_backend
    depends_on:
      - mongo
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/labdb
